### ISSUE TITLE
Websocket 通讯报错

### ISSUE THREAD

**Issue by houzy** [zhaojh329/rtty#110]
### rtty
* arch: arm64
* os: Debian 10
* version: 8.1.0

### rttys
* arch: amd64
* os: ubuntu 18.04
* version: 4.1.0

## Description
将服务端rttys（v4.1.0）和边端rtty（v8.1.0）都升级到最新版本，通过 rttys 管理页面打开边端网页，网页通过 websocket 通讯。
通过浏览器的 debug 工具可以看到边端网页请求的 websocket 发送成功，但是回复的消息始终收不到。同时在边端的 rtty 程序会打印出一个错误：err rtty[16854]: (net.c:131) connect failed: Invalid argument

**Comment by jxwuqingyan** [comment]
I have get this error when I start it
err rtty[19443]: (net.c:76) network connect failed: Connection refused

**Comment by cproape** [comment]
我也出现了这个问题，报错为2024/11/06 16:23:21 err rtty[19065]: (net.c:94) network connect timeout

**Comment by zhaojh329** [comment]
Fixed.
https://github.com/zhaojh329/rttys/commit/5eb0cc7e1bd49a7499caf93cf732f8b0976a10e2
