### ISSUE TITLE
arm-linux-gnueabihf-gcc 交叉编译，没有ssl，可以先关闭ssl，保证通过吗

### ISSUE THREAD

**Issue by MyNewFlint** [zhaojh329/rtty#119]
### rtty
* arch: crotex-a7
* os: Linux
* version: 5.14

### rttys
* arch:
* os:
* version:

## Description
cmake . -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -DCMAKE_FIND_ROOT_PATH=/tmp/rtty_install

-- The C compiler identification is GNU 4.9.4
-- Check for working C compiler: /opt/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc
-- Check for working C compiler: /opt/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Libev: /tmp/rtty_install/usr/local/lib/libev.so (found version "4.22") 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- Could NOT find WolfSSL (missing:  WOLFSSL_LIBRARY WOLFSSL_INCLUDE_DIR) 
-- Could NOT find MbedTLS (missing:  MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY MBEDTLS_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Warning at src/ssl/CMakeLists.txt:46 (message):
  No available SSL libraries found

-- Select  as the SSL backend
You have called ADD_LIBRARY for library xssl without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: Cannot determine link language for target "xssl".
CMake Error: CMake can not determine linker language for target: xssl

**Comment by zhaojh329** [comment]
```
-DSSL_SUPPORT=OFF
```

**Comment by MyNewFlint** [comment]
谢谢指导
