### ISSUE TITLE
Behind the nginx.

### ISSUE THREAD

**Issue by yunge** [zhaojh329/rtty#12]
When I used it behind nginx, it can't be used as a 'location'. The nginx.conf is like this:

location /rtty/ {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_pass http://127.0.0.1:5912;
}

**Comment by zhaojh329** [comment]
Why not run rttys directly?
