### ISSUE TITLE
请问是否支持通过代理来连接 rttys

### ISSUE THREAD

**Issue by ztj1993** [zhaojh329/rtty#129]
两种情况：

第一种：
假设服务器是不开放 5912 之类的端口，防火墙安全组会禁用掉所有的端口，只留下一个代理端口，经过代理才能访问内部服务。

第二种：
假设客户端不允许联网，或者不允许访问 rttys 的网络，只有通过代理，才能访问到 rttys。

---

请问 rtty 是否有计划增加通过代理访问 rttys，比如通过 socks5 代理等，而不是需要再额外搭建一个端口转发工具。

**Comment by zhaojh329** [comment]
支持。使用 nginx 配置反向代理即可。

**Comment by ztj1993** [comment]
这样仍然使用了额外的端口转发工具。
