### ISSUE TITLE
WSS support

### ISSUE THREAD

**Issue by yunge** [zhaojh329/rtty#13]
When I use rtty under Windows Chrome, I got such error:

vendor.46246f9d23c64a438174.js:1 Mixed Content: The page at 'https://mydomain:8443/?t=1520435728' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://mydomain:8443/ws?devid=myid'. This request has been blocked; this endpoint must be available over WSS.

**Comment by zhaojh329** [comment]
Fixed. Please upgrade the server.
