### ISSUE TITLE
error while loading shared libraries: libuwsc.so.2.0.1

### ISSUE THREAD

**Issue by yomun** [zhaojh329/rtty#14]
$ sudo rtty -I 'ubuntu-1710' -h '192.168.0.100' -p 5912 -a -v -s -d 'My Device Description'
rtty: error while loading shared libraries: libuwsc.so.2.0.1: cannot open shared object file: No such file or directory

I got above error..
I have updated my system curl to latest
curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0

**Comment by zhaojh329** [comment]
sudo ldconfig
