### ISSUE TITLE
Deb/Rpm package

### ISSUE THREAD

**Issue by doctord88** [zhaojh329/rtty#16]
I'm struggling with the installation of rtty: I managed to compile everything correctly but the first time I tried to launch rtty I got an error of a missing library. I thought: No problem! Let's create symbolic links. This worked for a couple of missing file but then I had to stop because the library libblobmsg_json.so is nowhere to be found, no matter where I link it. This is the error: "rtty: error while loading shared libraries: libblobmsg_json.so: cannot open shared object file: No such file or directory".

I tried by cloning from HEAD but also from the 4.1.1, with both ubuntu 16.04 and debian 9, 64 bit.

Do you have any idea why?

Do you think it would be possible to have a deb package or at least an install script so that everything is taken care of automatically?

Thanks in advance

**Comment by doctord88** [comment]
Never mind for the library not working. I just needed to run ldconfig.

But I would gladly use a deb package for this awesome piece of software, do you think it would be possible?

**Comment by zhaojh329** [comment]
Open the context menu with the shortcut key: Ctrl+Shift+F.

**Comment by doctord88** [comment]
Thank you very much.
