### ISSUE TITLE
Segmentation fault at reconnect by double onclose()?

### ISSUE THREAD

**Issue by spot62** [zhaojh329/rtty#17]
When the server rttys restarts, the client crashes instead of reconnecting
Is it because of double closing? Or what?

```
rtty version 4.1.1
onopen
(uwsc.c:440) Ping server, no response
:Resource temporarily unavailable
onclose
onclose
./rtty.sh: line 9: 15091 Segmentation fault      (core dumped) ./rtty -I ${ID} -h ${HOST} -p 5912 -P 60 -a -v -s -d "${DESC}"
```

Thank you

**Comment by zhaojh329** [comment]
This is bug of libuwsc, now I had fixed it.
Please see:
https://github.com/zhaojh329/libuwsc/commits/master
https://github.com/openwrt/packages/pull/6054

Thanks.
