### ISSUE TITLE
client 段错误

### ISSUE THREAD

**Issue by KevinWL** [zhaojh329/rtty#22]
(main.c:562) rtty version 5.1.0                                    
(main.c:415) onopen                                                
(main.c:149) New session:114d60eea1186ec3850bd841e6f665a5          
(main.c:422) onerror:1                                                                                          
(main.c:429) onclose                                               
(main.c:73) Del session:114d60eea1186ec3850bd841e6f665a5           
Segmentation fault                                                 
版本 client openwrt 5.10  server 2.1.1
server 部署在阿里云上，client openwrt 上， 当从页面登录 cat 一个较大文件（2M 左右）出现此问题，必现。加上-P  10 后报错信息如下：
root@FlexThinEdge:~# rtty -h 4xx.xx.xx -p 5913 -a  -I 000BABF59BA4 -v -P 10         
(main.c:562) rtty version 5.1.0                                                       
                                                                                      
(main.c:415) onopen                                                                   
                                                                                      
(main.c:149) New session:12debde0f3545fc991dd9d9c2b2c1b2a                             
                                                                                      
(uwsc.c:468) Ping server, no response                                                 
:Resource temporarily unavailable

**Comment by spot62** [comment]
this line 
https://github.com/zhaojh329/libuwsc/blob/513aaabb1340d65c1f773dc455ed7066d84a8853/src/uwsc.c#L53
do recursion there:
https://github.com/zhaojh329/libuwsc/blob/513aaabb1340d65c1f773dc455ed7066d84a8853/src/uwsc.c#L429
and
https://github.com/zhaojh329/libuwsc/blob/513aaabb1340d65c1f773dc455ed7066d84a8853/src/uwsc.c#L469
not returned

**Comment by zhaojh329** [comment]
Can you make a PR?
https://github.com/zhaojh329/rtty/blob/master/CONTRIBUTING.md
