### ISSUE TITLE
error v6.2.0

### ISSUE THREAD

**Issue by nelayan** [zhaojh329/rtty#26]
rtty
(main.c:629) libuwsc version 3.0.3
(main.c:630) rtty version 6.2.0
(uwsc.c:229) verify Sec-WebSocket-Accept failed
(main.c:469) onerror:2: Invalid header
(uwsc.c:229) verify Sec-WebSocket-Accept failed
(main.c:469) onerror:2: Invalid header

rttys
2018/09/25 21:46:29 go version: go1.10.1 linux/amd64
2018/09/25 21:46:29 rttys version: 2.4.0
2018/09/25 21:46:29 Listen on:  5912 SSL off
2018/09/25 21:46:39 New device:id('My-device-ID'), description('My Device Description')
2018/09/25 21:46:39 Dead device:id('My-device-ID'), description('My Device Description')

tested on rtty-openssl or rtty-nossl same error message.

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='18.06'
DISTRIB_REVISION='r7324-05606de1aa'
DISTRIB_TARGET='ar71xx/generic'
DISTRIB_ARCH='mips_24kc'

**Comment by zhaojh329** [comment]
Fixed.

This is a bug of libuwsc.

https://github.com/zhaojh329/libuwsc/commit/05120773d97c4c963d5c106993e4083ca19a47e4

**Comment by nelayan** [comment]
thank you.
