### ISSUE TITLE
rtty client make error on CentsOS 6.8

### ISSUE THREAD

**Issue by zhang1g2** [zhaojh329/rtty#32]
**when run ./install.sh, some errors occur like:**

......
Receiving objects: 100% (2182/2182), 6.36 MiB | 14 KiB/s, done.
Resolving deltas: 100% (1378/1378), done.
-- The C compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Libev (missing: LIBEV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibev.cmake:25 (find_package_handle_standard_args)
  src/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/rtty-build/libuwsc/CMakeFiles/CMakeOutput.log".

**Comment by zhaojh329** [comment]
Thanks. I've fixed it. Please try again.
