### ISSUE TITLE
cat查看大文件导致客户端出错退出

### ISSUE THREAD

**Issue by baidxi** [zhaojh329/rtty#35]
cat 查看/var/log/下日志的时候出现客户端退出的情况。
日志文件200多KB
出现以下错误，经测试为100%重现。
Sat Dec  1 09:22:19 2018 daemon.err rtty: (main.c:276) onerror:1: write error
Sat Dec  1 09:22:24 2018 daemon.err rtty: (main.c:276) onerror:7: ssl handshake failed
Sat Dec  1 09:22:29 2018 daemon.err rtty: (main.c:276) onerror:1: read error
Sat Dec  1 09:23:58 2018 auth.info login[3636]: root login on 'pts/1'
Sat Dec  1 09:24:04 2018 daemon.err rtty: (main.c:276) onerror:1: write error

**Comment by zhaojh329** [comment]
暂未复现。请描述具体环境。
