### ISSUE TITLE
SegFault in latest main.c::change_winsize

### ISSUE THREAD

**Issue by apedev7** [zhaojh329/rtty#41]
The function main.c::change_winsize segfault, caused by NULL tty.

This is easily reproducible by symlink /bin/login to a shell script that exits immediately without doing anything.

The underlaying sequence appears to be
1. SIGCHLD queued,
2. The window size message queued
3. SIGCHLD processed to destroy the SID
4. change_winsize is called with the destroyed SID.
5. tty pointer thus is null

**Comment by zhaojh329** [comment]
Thanks.

**Comment by zhaojh329** [comment]
Need to determine the value of tty, if it is NULL, return directly.

**Comment by zhaojh329** [comment]
![image](https://user-images.githubusercontent.com/28673295/55944690-b9d53000-5c7b-11e9-92a8-2938f16d6b47.png)

**Comment by zhaojh329** [comment]
Can you make a PR to fix it?

**Comment by apedev7** [comment]
I tested your fix, and it works fine.

I'm fine with your pushing the fix into the repo directly; I don't need the credit.
