### ISSUE TITLE
onclose:1006: unexpected EOF

### ISSUE THREAD

**Issue by fffflyon** [zhaojh329/rtty#42]
onclose:1006: unexpected EOF

**Comment by zhaojh329** [comment]
It should be that your server rttys is abnormally closed.

**Comment by fffflyon** [comment]
but the server is ok. I use another client to connect the server is succeed.   And my services is from the release.

**Comment by zhaojh329** [comment]
The program does have unstable factors. I have developed it alone and my
experience is limited.
