### ISSUE TITLE
rtty fails to start on latest openwrt

### ISSUE THREAD

**Issue by KazukiShimada** [zhaojh329/rtty#43]
Hi.
I tested rtty on latest openwrt which was built on buildroot. But it failed to start.
After some digging, I found rtty requires Libuwsc 3.2,
https://github.com/zhaojh329/rtty/blob/master/src/CMakeLists.txt
on the other hand, libuwsc version is 3.3.1 in buildroot.
Can you update the version of rtty ?
Thanks.

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/rtty/blob/master/OPENWRT.md#compile-it-yourself
