### ISSUE TITLE
Problem login client

### ISSUE THREAD

**Issue by lordbasex** [zhaojh329/rtty#45]
Hello good afternoon.
An excellent project.

I have a problem with the rtty client daemon does not accept my password.
The remote server is a minimum installation centos 7

This is the log.

19 de agosto 15:51:58 [localhost] rtty: (main.c: 122) Error de lectura de pty: Recurso temporalmente no disponible

tail -f /var/log/audit/audit.log
type=USER_AUTH msg=audit(1566241343.428:34632): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'
type=USER_LOGIN msg=audit(1566241345.152:34633): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=login id=0 exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'

type=USER_AUTH msg=audit(1566241379.399:34634): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'

type=USER_AUTH msg=audit(1566241343.428:34632): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'
type=USER_LOGIN msg=audit(1566241345.152:34633): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=login id=0 exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'

type=USER_AUTH msg=audit(1566241379.399:34634): pid=2007 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/login" hostname=dpbx addr=? terminal=pts/1 res=failed'

tail -f /var/log/messages
Aug 19 16:01:38 [localhost] rtty: (main.c:227) non-existent sid: 2
Aug 19 16:01:59 [localhost] rtty: (main.c:122) Read from pty failed: Resource temporarily unavailable

**Comment by zhaojh329** [comment]
#46
