### ISSUE TITLE
rtty如何离线安装

### ISSUE THREAD

**Issue by litongjava** [zhaojh329/rtty#48]
现在rtty是在线安装
但是改如何离线安装呢?
1.下载依赖包
2.执行什么命令编译这些依赖包
3.执行什么命令编译生成客户端

附上CentOS-7客户端开机自启脚本
vi /lib/systemd/system/rttyc.service
```
[Unit]
Description=rttyc
After=network.target network-online.target syslog.target
Wants=network.target network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/rtty -I 'fedora' -h '192.168.99.214' -p 5912 -a -v -t b7dd7ccb255a4a84562c76abae0a232b

[Install]
WantedBy=multi-user.target
```

```
systemctl start rttyc
systemctl enable rttyc
```

**Comment by zhaojh329** [comment]
如果是x86，参考https://raw.githubusercontent.com/zhaojh329/rtty/master/tools/install.sh
如果是嵌入式平台：https://github.com/zhaojh329/rtty/blob/master/CROSS_COMPILE.md

**Comment by litongjava** [comment]
要安装一些依赖包,确实不方便
可以将 rtty编译一个静态文件,复制到服务器上就可以用,例如frpc,frp的客户端程序

**Comment by zhaojh329** [comment]
C代码不具有跨平台能力。

**Comment by litongjava** [comment]
在CentOS-7上离线安装
```
yum install -y gcc cmake libev-devel openssl-devel
```
安装libuwsc
下载https://github.com/zhaojh329/libuwsc/releases
mkdir /opt/package/libuwsc -p && cd /opt/package/libuwsc
上传libuwsc-3.3.2.tar.gz到此目录
```
tar -xf libuwsc-3.3.2.tar.gz
cd libuwsc-3.3.2
cmake . && make install
```
安装rtty
下载https://github.com/zhaojh329/rtty/releases
mkdir -p /opt/package/rtty && cd /opt/package/rtty
#上传rtty到此目录下
```
tar -xf rtty-6.6.1.tar.gz
cd rtty-6.6.1
cmake . && make install
```
设置ld
```
echo "/usr/local/lib" > /etc/ld.so.conf.d/rtty
ldconfig -f /etc/ld.so.conf.d/rtty
```
启动rtty客户端
```
rtty -I 'fedora' -h '192.168.99.214' -p 5912 -a -v -s -t b7dd7ccb255a4a84562c76abae0a232b
```
