### ISSUE TITLE
For Windows

### ISSUE THREAD

**Issue by Gobiviswa** [zhaojh329/rtty#49]
Hi Team,

First of all, Congrats and Thanks for this excellent project. 
I am looking to compile this for the windows machine. Is there any possibilities for that?

**Comment by zhaojh329** [comment]
go get -u github.com/zhaojh329/rtty

**Comment by Gobiviswa** [comment]
I am not able to do go get -u github.com/zhaojh329/rtty. It is saying no go files in ../github.com/zhaojh329/rtty.  I hope client is not a go project.

**Comment by zhaojh329** [comment]
Sorry, I thought you were talking about the rttys project.
The client rtty does not support Windows, only Linux. But you can use it in wsl for Windows.
