### ISSUE TITLE
rtty session corruption at file transmission

### ISSUE THREAD

**Issue by derplayer** [zhaojh329/rtty#56]
Hey,

i have rtty on an openwrt device. I transmitted a bigger file (~16mb) but cancelled the transmission.
This broke the rtty service, and the terminal output was totally corrupted/garbage in rttys. After a reboot, the device also didn't appeared anymore in rttys. (the service still ran on the device)
Only a clean firmware reflash helped. Do you know more about this behaviour?

Cheers,

**Comment by zhaojh329** [comment]
This may be a bug.

**Comment by zhaojh329** [comment]
Please update rtty to 7.1.0.
