### ISSUE TITLE
openwrt 15.05 无法clone

### ISSUE THREAD

**Issue by Torchwoods** [zhaojh329/rtty#57]
按照说明在openwrt15.05里面源码的feed中添加源，在update的时候出现无法clone
日志如下：
`
Updating feed 'rtty' from 'https://github.com/zhaojh329/rtty.git;openwrt-lede' ...
Cloning into './feeds/rtty'...
warning: Could not find remote branch openwrt-lede to clone.
fatal: Remote branch openwrt-lede not found in upstream origin
failed.

`

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/rtty/tree/openwrt-package 
将这个移植到openwrt15.05

**Comment by Torchwoods** [comment]
> https://github.com/zhaojh329/rtty/tree/openwrt-package
> 将这个移植到openwrt15.05
编译出的文件缺少一个/bin/login文件导致程序无法运行
