### ISSUE TITLE
rtty一直断开重连

### ISSUE THREAD

**Issue by Torchwoods** [zhaojh329/rtty#58]
日志：
Thu Feb  6 16:44:46 2020 daemon.err rtty: (rtty.c:454) Inactive too long time
Thu Feb  6 16:44:47 2020 daemon.err rtty: (rtty.c:448) rtty reconnecting...

**Comment by zhaojh329** [comment]
看下服务器日志：cat /var/log/rttys.log

**Comment by Torchwoods** [comment]
time="2020-02-05T16:37:54+08:00" level=info msg="Delete session: 88e188341c6115692ba54daf766b52de"
time="2020-02-05T20:21:08+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303069"
time="2020-02-05T20:21:08+08:00" level=info msg="Died device:202020303069"
time="2020-02-05T20:21:46+08:00" level=info msg="New device:202020303069"
time="2020-02-05T20:29:42+08:00" level=info msg="New session:d2fe0ee927a30e8d8e33dbac3c34d029"
time="2020-02-05T20:32:09+08:00" level=info msg="Delete session: d2fe0ee927a30e8d8e33dbac3c34d029"
time="2020-02-05T22:27:16+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303069"
time="2020-02-05T22:27:16+08:00" level=info msg="Died device:202020303069"
time="2020-02-05T22:27:56+08:00" level=info msg="New device:202020303069"
time="2020-02-05T23:13:35+08:00" level=info msg="New session:c540b9b64640dda9f63614b18f6770b7"
time="2020-02-05T23:42:55+08:00" level=info msg="Delete session: c540b9b64640dda9f63614b18f6770b7"
time="2020-02-05T23:59:55+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303294"
time="2020-02-05T23:59:55+08:00" level=info msg="Died device:202020303294"
time="2020-02-06T00:00:36+08:00" level=info msg="New device:202020303294"
time="2020-02-06T00:58:36+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303069"
time="2020-02-06T00:58:36+08:00" level=info msg="Died device:202020303069"
time="2020-02-06T00:59:13+08:00" level=info msg="New device:202020303069"
time="2020-02-06T01:00:16+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303294"
time="2020-02-06T01:00:16+08:00" level=info msg="Died device:202020303294"
time="2020-02-06T01:01:22+08:00" level=info msg="New device:202020303294"
time="2020-02-06T03:49:32+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303294"
time="2020-02-06T03:49:32+08:00" level=info msg="Died device:202020303294"
time="2020-02-06T03:50:30+08:00" level=info msg="New device:202020303294"
time="2020-02-06T10:50:58+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303069"
time="2020-02-06T10:50:58+08:00" level=info msg="Died device:202020303069"
time="2020-02-06T10:51:40+08:00" level=info msg="New device:202020303069"
time="2020-02-06T12:28:48+08:00" level=info msg="New device:202020303393"
time="2020-02-06T13:26:52+08:00" level=info msg="New session:ef22fc69546058bfb7a0fbca20d3cdb0"
time="2020-02-06T13:42:47+08:00" level=info msg="Delete session: ef22fc69546058bfb7a0fbca20d3cdb0"
time="2020-02-06T15:00:18+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303393"
time="2020-02-06T15:00:18+08:00" level=info msg="Died device:202020303393"
time="2020-02-06T15:11:00+08:00" level=error msg="Inactive device in long time, now kill it: %s202020303069"
time="2020-02-06T15:11:00+08:00" level=info msg="Died device:202020303069"

**Comment by Torchwoods** [comment]
没有这台设备的信息

**Comment by Torchwoods** [comment]
是不是rttys也要升级到3.0？我服务器上应该是2.10.3

**Comment by Torchwoods** [comment]
替换rttys为3.0.0 web界面崩溃
ERRO[0000] lstat ./rttys.crt: no such file or directory 
ERRO[0000] lstat ./rttys.key: no such file or directory 
INFO[0000] Go Version: go1.13                           
INFO[0000] Go OS/Arch: linux/amd64                      
INFO[0000] Rttys Version: 3.0.0                         
INFO[0000] Git Commit: 38e7482                          
INFO[0000] Build Time: 2020-01-31T18:03:29+0800         
INFO[0000] Listen device on: :5912 SSL off              
INFO[0000] Listen user on: :5913 SSL off                
INFO[0001] New device: 202020303069                     
ERRO[0008] Inactive device in long time, now kill it:  2020-02-06 19:27:19.694033365 +0800 CST m=+8.587491581 
ERRO[0008] Inactive device in long time, now kill it:  2020-02-06 19:27:19.719581476 +0800 CST m=+8.613039692 
ERRO[0008] Inactive device in long time, now kill it:  2020-02-06 19:27:19.806000775 +0800 CST m=+8.699458987 
ERRO[0008] Inactive device in long time, now kill it:  2020-02-06 19:27:19.81829298 +0800 CST m=+8.711751187 
ERRO[0009] bufio: buffer full                           
INFO[0009] Device '' closed                             
ERRO[0009] bufio: buffer full                           
INFO[0009] Device '' closed                             
ERRO[0009] bufio: buffer full                           
INFO[0009] Device '' closed                             
ERRO[0009] bufio: buffer full                           
INFO[0009] Device '' closed                             
ERRO[0022] Inactive device in long time, now kill it:  2020-02-06 19:27:33.711781674 +0800 CST m=+22.605239885 
ERRO[0022] Inactive device in long time, now kill it:  2020-02-06 19:27:33.744126887 +0800 CST m=+22.637585098 
ERRO[0022] Inactive device in long time, now kill it:  2020-02-06 19:27:33.872399264 +0800 CST m=+22.765857476 
ERRO[0022] Inactive device in long time, now kill it:  2020-02-06 19:27:33.884524746 +0800 CST m=+22.777982952 
ERRO[0023] bufio: buffer full                           
INFO[0023] Device '' closed                             
ERRO[0023] bufio: buffer full                           
INFO[0023] Device '' closed                             
ERRO[0023] bufio: buffer full                           
INFO[0023] Device '' closed                             
ERRO[0023] bufio: buffer full                           
INFO[0023] Device '' closed

**Comment by zhaojh329** [comment]
全部升级到最新版本。
