### ISSUE TITLE
I suggest putting the root permission check at the later point建议判断root权限放在 getopt后面

### ISSUE THREAD

**Issue by axlrose** [zhaojh329/rtty#6]
rtty -h 的时候提示 Operation not permitted
其实像查看帮助不需要root权限
所以建议将 if (setuid(0) < 0) { 放在getopt后面

I suggest putting the root permission check at the later point

**Comment by zhaojh329** [comment]
你可以直接提交PR。
You can make a PR.

**Comment by zhaojh329** [comment]
done.
