### ISSUE TITLE
第二次点击连接显示会话已满

### ISSUE THREAD

**Issue by ajdwfnhaps** [zhaojh329/rtty#61]
![image](https://user-images.githubusercontent.com/11205717/75413634-06dbf680-5961-11ea-9c8a-805cf4edba92.png)

服务器版本：v3.1.1
![image](https://user-images.githubusercontent.com/11205717/75413704-41459380-5961-11ea-82ad-0207fa47dd21.png)

服务端配置：
![image](https://user-images.githubusercontent.com/11205717/75413870-c16bf900-5961-11ea-81b5-d53452cada77.png)

客户端版本：7.1.1
![image](https://user-images.githubusercontent.com/11205717/75413721-4c98bf00-5961-11ea-93ff-3f876afa7cb2.png)

**Comment by zhaojh329** [comment]
我本地测试未复现。请尝试在自己的环境中调试，找出问题。

**Comment by zhaojh329** [comment]
已修复。https://github.com/zhaojh329/rtty/commit/22ec200d7cd0daf8c7c4050e70a806dc14ba1978

**Comment by ajdwfnhaps** [comment]
感谢作者
