### ISSUE TITLE
rtty客户端连接不到服务器时，内存会一直增长

### ISSUE THREAD

**Issue by su20131531010** [zhaojh329/rtty#63]
在openwrt上，使用rtty客户端连接服务器时，如果连接不到服务器，rtty的内存会一直增长，直到把内存撑爆，如下图内存增长情况（每小时3M左右）

![微信图片_20200319150048](https://user-images.githubusercontent.com/36102353/77040215-74c08e80-69f2-11ea-9b43-1387e1186a49.png)

**Comment by zhaojh329** [comment]
如果不是最新版，请先升级rtty和rttys到最新版再尝试。
