### ISSUE TITLE
does support command line to transfer file?

### ISSUE THREAD

**Issue by zhifeng456** [zhaojh329/rtty#67]
Hello zhao,
  if without using webssh, i want to use command line for automation easily,does there are have the way to transfer the file in terminal command line?
like below:
sh /root/sendcmd.sh 061122334481 rtty -S /tmp/install.log,
if use web login, there are no problem, if use the above command, which just print the content of the file.
  as you know, there will not comfortable if there are many devices.
  thanks.

**Comment by zhaojh329** [comment]
Not implemented.
