### ISSUE TITLE
按照其它嵌入式Linux平台方法配置，编译rtty时报错

### ISSUE THREAD

**Issue by zesongHuang** [zhaojh329/rtty#69]
root@localhost:/usr/rtty# cmake . -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_FIND_ROOT_PATH=/tmp/rtty_install
-- Could NOT find WOLFSSL (missing: WOLFSSL_LIBRARY WOLFSSL_INCLUDE_DIR) 
-- Could NOT find MbedTLS (missing: MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY MBEDTLS_INCLUDE_DIR) 
-- Select OpenSSL as the SSL backend
-- Configuring done
CMake Error at src/CMakeLists.txt:93 (add_executable):
  Cannot find source file:

    buffer/buffer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: rtty
CMake Error: Cannot determine link language for target "rtty".
-- Generating done
-- Build files have been written to: /usr/rtty

我还需要下载   WOLFSSL   MbedTLS   ？
这是我的交叉编译器：aarch64-linux-gnu-gcc
我分别下载了（WOLFSSL   MbedTLS）这个能再嵌入式硬件中编译吗/

**Comment by zhaojh329** [comment]
git clone --recursive https://github.com/zhaojh329/rtty.git
