### ISSUE TITLE
编译好的rtty拷贝到设备后，在rttys页面连接设备时账号密码一直错误的问题

### ISSUE THREAD

**Issue by zesongHuang** [zhaojh329/rtty#71]
您好：
我硬件设备的 密码和用户名都是 root  但是我在后台连接的时候一直报错  Login incorrect
 直到我删除了etc/security 的文件 才能连接硬件设备？ 请问有什么官方方式解决此问题吗？还有我这是什么原因造成的呢？ 劳烦作者解惑 感谢 🙇‍

**Comment by zhaojh329** [comment]
rtty的登陆是直接调用 /bin/login 程序。

**Comment by zesongHuang** [comment]
但是我在设备登录没有问题，只有页面连接设备才会出现这个问题

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/rtty/issues/46
看下这个是否能帮到您。
