### ISSUE TITLE
Excause me!I create rtty ipk error,with follow error infomation,how to fix it?thanks!

### ISSUE THREAD

**Issue by unflypig** [zhaojh329/rtty#75]
CMake Error at /home/lzq/work/work2019/qsdk_201904/qca-networking-2017-spf-5-0-3_qca_oem.git/qsdk/staging_dir/host/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find Libev (missing: LIBEV_LIBRARY LIBEV_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/lzq/work/work2019/qsdk_201904/qca-networking-2017-spf-5-0-3_qca_oem.git/qsdk/staging_dir/host/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibev.cmake:25 (find_package_handle_standard_args)
  src/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by qubitter** [comment]
You need to install libev - depending on platform the command to do it will be different. There's instructions in the README.
