### ISSUE TITLE
LEDE 17.01.7 源码编译rtty version 7.1.4  rtty -R -S 无效

### ISSUE THREAD

**Issue by liangyuan64** [zhaojh329/rtty#79]
LEDE 17.01.7 源码编译rtty version 7.1.4
rtty -R -S无效果,已确认rttys没问题(与其它设备测试过可用).

rtty -R
除连接外无日志

rtty -S日志
2020/09/11 06:20:23 (main.c:161) rtty version 7.1.4
2020/09/11 06:20:23 (rtty.c:400) connected to server
2020/09/11 06:20:23 (rtty.c:302) register success
2020/09/11 06:20:37 (rtty.c:191) new tty: 0
2020/09/11 06:21:21 (file.c:181) upload file is busy

root权限执行uid=0(root) gid=0(root)

**Comment by zhaojh329** [comment]
![image](https://user-images.githubusercontent.com/28673295/93016254-6b575e00-f5f2-11ea-8429-d87c87aa7980.png)

**Comment by zhaojh329** [comment]
已修复。https://github.com/zhaojh329/rtty/commit/95785fbc782102a182f85f6838e3e1ebb80c721d
