### ISSUE TITLE
【提问】大佬有没有考虑过将 rtty 使用 go 语言实现

### ISSUE THREAD

**Issue by ngxlua** [zhaojh329/rtty#81]
这样可以让 rtty 和 rttys 进行更深的整合，服务端和客户端都是 go 语言编码， 降低社区的参与难度

**Comment by zhaojh329** [comment]
开发 rtty 的初衷就是针对嵌入式Linux设备。C语言更适合。

**Comment by xiaoweihong** [comment]
c的动态库不好处理，同求go语言版本

**Comment by zhaojh329** [comment]
如果用 go 语言开发，就简单多了。网上很多类似的项目。
