### ISSUE TITLE
远程调用cmd命令 拿到token后， 去获取结果，一直返回pending?

### ISSUE THREAD

**Issue by xjgaod** [zhaojh329/rtty#84]
![image](https://user-images.githubusercontent.com/36026206/104979293-e4ead700-5a3e-11eb-9dc5-c2df463d4c63.png)

**Comment by zhaojh329** [comment]
请使用最新版本。操作方式简化了。
https://github.com/zhaojh329/rtty/blob/master/COMMAND_ZH.md
