### ISSUE TITLE
使用最新rtty 按照README_ZH.md 的方式编译安装，在执行是一直出错

### ISSUE THREAD

**Issue by Misng** [zhaojh329/rtty#86]
使用最新rtty  按照README_ZH.md 的方式编译安装，在执行时一直出错，不知道发生了什么，我之前使用码云上的仓库进行过四次配置，是否会对此产生影响。

![图片](https://user-images.githubusercontent.com/16435001/106082064-fa55b480-6154-11eb-8cf8-068a2716be7c.png)

**Comment by Misng** [comment]
> hdp@ubuntu-vmware:~/Downloads/rtty/build$ sudo rtty -I '12345678' -h 'your-server' -p 19555 -a -v -d 'My Device Description'
2021/01/28 10:37:18 (main.c:161) rtty version 7.2.3
2021/01/28 10:37:18 (net.c:167) getaddrinfo failed: Name or service not known
2021/01/28 10:37:23 (rtty.c:446) rtty reconnecting...
2021/01/28 10:37:23 (net.c:167) getaddrinfo failed: Name or service not known
2021/01/28 10:37:29 (rtty.c:446) rtty reconnecting...
2021/01/28 10:37:29 (net.c:167) getaddrinfo failed: Name or service not known
2021/01/28 10:37:34 (rtty.c:446) rtty reconnecting...
2021/01/28 10:37:34 (net.c:167) getaddrinfo failed: Name or service not known
2021/01/28 10:37:40 (rtty.c:446) rtty reconnecting...


`hdp@ubuntu-vmware:~/Downloads/rtty/build$ curl -k https://192.168.0.113:19555/devs`
curl: (7) Failed to connect to 192.168.0.113 port 19555: Connection refused
`hdp@ubuntu-vmware:~/Downloads/rtty/build$ curl -k https://192.168.0.113:19555/devs`
curl: (7) Failed to connect to 192.168.0.113 port 19555: Connection refused
`hdp@ubuntu-vmware:~/Downloads/rtty/build$ ifconfig`
ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.113  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::250:56ff:fe3c:3685  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:3c:36:85  txqueuelen 1000  (Ethernet)
        RX packets 115639  bytes 121213378 (121.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24157  bytes 1905707 (1.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by Misng** [comment]
我是在虚拟机的Ubuntu 18.04.5 LTS 使用的

**Comment by zhaojh329** [comment]
'your-server' 是什么？不替换成你的实际服务器地址吗？

**Comment by Misng** [comment]
> 
> 
> 'your-server' 是什么？不替换成你的实际服务器地址吗？
> 
> https://github.com/zhaojh329/rttys/blob/master/README_ZH.md

我以为那是一个服务器别名。-_-||
