### ISSUE TITLE
文件传输提示no space

### ISSUE THREAD

**Issue by AndyDeee** [zhaojh329/rtty#92]
### rtty
* arch: ARM926EJ-S rev 5 (v5l)
* os: Linux version 2.6.35.4
* version: 7.4.0

### rttys
* arch: x86-64
* os: centOS 7-64
* version: 3.5.0

## Description
上传时网页提示: no space.
客户端提示: download file fail: not found mount point of /mnt/XXX
 实际原因是/etc/mtab不存在导致find_mount_point出错(#file: utils.c:123)
需要支持/etc/fstab方式
另外，当前嵌入式设备使用的fstab并没有显示动态挂载设备，例如mount启动挂载，需要支持
```
mtab_fp = setmntent("/etc/mtab", "r");
if (!mtab_fp)
        return NULL;
```

**Comment by zhaojh329** [comment]
可以提交一个 PR 吗？

**Comment by AndyDeee** [comment]
fstab比较容易支持，只需要判断前面的mtab是否读取为空，但是动态挂载设备如何计算空间，还没有好的通用解决方案

**Comment by zhaojh329** [comment]
```
lrwxrwxrwx    1 root     root            12 Apr 16 01:39 /etc/mtab -> /proc/mounts
```
/etc/mtab 事实上是链接到 /proc/mounts 的

**Comment by shakespark** [comment]
我这边的嵌入式设备没有mtab,fstab也是空的，所有分区是直接cmdline里挂载，于是也遇到了这个问题。
目前解决是直接用statvfs去获取对应分区的可用容量，测试后是可以上传的。
请问在检查容量前要去查分区表的目的是什么呢？

**Comment by guangjieMVP** [comment]
> ```
> lrwxrwxrwx    1 root     root            12 Apr 16 01:39 /etc/mtab -> /proc/mounts
> ```
> 
> /etc/mtab 事实上是链接到 /proc/mounts 的

做了这个链接问题就解决？

**Comment by guangjieMVP** [comment]
> /etc/mtab



> ```
> lrwxrwxrwx    1 root     root            12 Apr 16 01:39 /etc/mtab -> /proc/mounts
> ```
> 
> /etc/mtab 事实上是链接到 /proc/mounts 的

加上这个链接问题就解决了么
