### ISSUE TITLE
If set rtty as  systemctl service, rtty server pages has layout issue

### ISSUE THREAD

**Issue by TimorChow** [zhaojh329/rtty#94]
### rtty
* arch:arm32v7
* os:Debian
* version:v7.4.0

### rttys
* arch:amd64
* os: Amazon Linux 2 AMI
* version: v3.5.0

## Description
While setup as rtty.service, and `systemctl start rtty`, rtty is connected, but if you go to terminal, there are some layout issue:
- no color
- Backspace not working properly
![image](https://user-images.githubusercontent.com/18365403/117177276-d54d8f00-ad9e-11eb-9ad1-aa809b60a023.png)

But if I run `start.sh`, the service is normal, rttys dashboard is working properly.

```
[Unit]
Description=Rtty Client Service
After=network.target network-online.target syslog.target
Wants=network.target network-online.target

[Service]
Type=simple
User=pi
Restart=on-failure
RestartSec=5s
ExecStart=/usr/bin/bash /home/pi/Project/start.sh

[Install]
WantedBy=multi-user.target
```

This is `start.sh`
```
macAddr=$(cat /sys/class/net/eth0/address)
sudo rtty -I "${macAddr//:}" -h 'hub.shoveldigital.com' -p 5912 -a -v -f pi -d "Testing" -t 2ff113bc4d5c57a1105b23fb082d24e5
```

And thank you for sharing this powerful program!

**Comment by TimorChow** [comment]
More pics
![image](https://user-images.githubusercontent.com/18365403/117179318-0038e280-ada1-11eb-8bab-ec1d8d8604d1.png)

**Comment by TimorChow** [comment]
Problem was solved by exec `export TERM=xterm` after start the ssh session

Reference: https://www.linuxquestions.org/questions/debian-26/terminal-error-with-vi-editor-376401/

**Comment by zhaojh329** [comment]
Is there a solution to make `rtty` adapt to all systems?

**Comment by zhaojh329** [comment]
![image](https://user-images.githubusercontent.com/28673295/117540877-d4895700-b043-11eb-8cce-1940caa8af35.png)
![image](https://user-images.githubusercontent.com/28673295/117540926-0c909a00-b044-11eb-971d-f4616499b0c9.png)

**Comment by TimorChow** [comment]
> Is there a solution to make `rtty` adapt to all systems?

Thank you for this reply. 

This is from my server:
![image](https://user-images.githubusercontent.com/18365403/117722710-695c9380-b1af-11eb-89ad-07add32fbc9b.png)
