### ISSUE TITLE
交叉编译时报错，求大神给看看

### ISSUE THREAD

**Issue by matthuo333** [zhaojh329/rtty#99]
### rtty
* arch: arm64
* os: Coreelec
* version: 

### rttys
* arch:
* os:
* version:

## Description
在交叉编译时报错：

[  7%] Building C object src/ssl/CMakeFiles/xssl.dir/openssl.c.o
In file included from /usr/include/openssl/ssl.h:146:0,
                 from /root/rtty/src/ssl/openssl.c:51:
/usr/include/openssl/e_os2.h:56:33: fatal error: openssl/opensslconf.h: No such file or directory
compilation terminated.
src/ssl/CMakeFiles/xssl.dir/build.make:62: recipe for target 'src/ssl/CMakeFiles/xssl.dir/openssl.c.o' failed
make[2]: *** [src/ssl/CMakeFiles/xssl.dir/openssl.c.o] Error 1
CMakeFiles/Makefile2:153: recipe for target 'src/ssl/CMakeFiles/xssl.dir/all' failed
make[1]: *** [src/ssl/CMakeFiles/xssl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Formating code blocks by wrapping them with pairs of ```
```

**Comment by matthuo333** [comment]
openssl 编译安装 1.0.2 后解决了。但是又出现之下问题：

![image](https://user-images.githubusercontent.com/55862904/137370968-ae53364b-28b1-487a-ad26-dcccc8cd9993.png)

**Comment by matthuo333** [comment]
我最终在编译前，禁用了ssl. 编译完了。但是，运行后，又出现如下提示：

rtty: error while loading shared libraries: /usr/lib/libev.so.4: internal error

**Comment by matthuo333** [comment]
按照说明，已经做了软连接。仍然这个提示。

**Comment by matthuo333** [comment]
> 还是/usr/lib/libev.so.4有问题。运行时只需要这个so，你不做软链接也可以的

编译后，只有这个文件：ibev.so.4.0.0   其他默认都是软链接文件

**Comment by matthuo333** [comment]
![image](https://user-images.githubusercontent.com/55862904/137837626-05ca755f-ec16-4db6-8bc1-a1e61c4ea833.png)

**Comment by shakespark** [comment]
附上我昨晚交叉编译(arm7架构)的步骤供参考

export GCC_ARM_PATH="/home/dtvl/FUFENG/r14_ltev2x_app/build/toolchain/gcc-4.9-2016.02-x86_64_arm-linux-gnueabi"
export GCC_ARM_GCC="${GCC_ARM_PATH}/bin/arm-linux-gnueabi-gcc"
export GCC_ARM_GXX="${GCC_ARM_PATH}/bin/arm-linux-gnueabi-g++"
export GCC_ARM_LIB_PATH="${GCC_ARM_PATH}/lib"
export GCC_ARM_INCLUDE_PATH="${GCC_ARM_PATH}/include"

编译libev
export LIBEV_PATH="/home/dtvl/rtty-client/libev"
./configure --prefix=${LIBEV_PATH}/OUT --host=arm-linux-gnueabi CC=${GCC_ARM_GCC} CXX=${GCC_ARM_GXX} LDFLAGS="-L${GCC_ARM_LIB_PATH}" CPPFLAGS="-I${GCC_ARM_INCLUDE_PATH}"
make install

编译rtty
cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/dtvl/rtty-client/rtty/OUT . -DCMAKE_C_COMPILER=${GCC_ARM_GCC} -DCMAKE_FIND_ROOT_PATH=${LIBEV_PATH}/OUT -DSSL_SUPPORT=OFF
make install

**Comment by matthuo333** [comment]
> 附上我昨晚交叉编译(arm7架构)的步骤供参考
> 
> 
> 
> export GCC_ARM_PATH="/home/dtvl/xxx/r14_ltev2x_app/build/toolchain/gcc-4.9-2016.02-x86_64_arm-linux-gnueabi"
> 
> export GCC_ARM_GCC="${GCC_ARM_PATH}/bin/arm-linux-gnueabi-gcc"
> 
> export GCC_ARM_GXX="${GCC_ARM_PATH}/bin/arm-linux-gnueabi-g++"
> 
> export GCC_ARM_LIB_PATH="${GCC_ARM_PATH}/lib"
> 
> export GCC_ARM_INCLUDE_PATH="${GCC_ARM_PATH}/include"
> 
> 
> 
> 编译libev
> 
> export LIBEV_PATH="/home/dtvl/rtty-client/libev"
> 
> ./configure --prefix=${LIBEV_PATH}/OUT --host=arm-linux-gnueabi CC=${GCC_ARM_GCC} CXX=${GCC_ARM_GXX} LDFLAGS="-L${GCC_ARM_LIB_PATH}" CPPFLAGS="-I${GCC_ARM_INCLUDE_PATH}"
> 
> make install
> 
> 
> 
> 编译rtty
> 
> cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/dtvl/rtty-client/rtty/OUT . -DCMAKE_C_COMPILER=${GCC_ARM_GCC} -DCMAKE_FIND_ROOT_PATH=${LIBEV_PATH}/OUT -DSSL_SUPPORT=OFF
> 
> make install

你的编译环境是什么系统？

**Comment by shakespark** [comment]
本机是ubuntu，交叉编译出arm7

**Comment by shakespark** [comment]
把你的交叉工具链路径传的正确就行。
如果你之前交叉编译工具链已经正常编出来你板子上可以跑的程序，那么这个也一样的编
